/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParticleTracking_GPU_Analyse */

#ifndef _Included_ParticleTracking_GPU_Analyse
#define _Included_ParticleTracking_GPU_Analyse
#ifdef __cplusplus
extern "C" {
#endif
#undef ParticleTracking_GPU_Analyse_VERSION
#define ParticleTracking_GPU_Analyse_VERSION 4L
#undef ParticleTracking_GPU_Analyse_TRACK_EXT
#define ParticleTracking_GPU_Analyse_TRACK_EXT 1.0f
#undef ParticleTracking_GPU_Analyse_TRACK_OFFSET
#define ParticleTracking_GPU_Analyse_TRACK_OFFSET 0.75f
/*
 * Class:     ParticleTracking_GPU_Analyse
 * Method:    cudaGaussFitter
 * Signature: (Ljava/lang/String;Ljava/lang/String;FFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_ParticleTracking_GPU_1Analyse_cudaGaussFitter
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
