/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParticleTracking_GPUAnalyse */

#ifndef _Included_ParticleTracking_GPUAnalyse
#define _Included_ParticleTracking_GPUAnalyse
#ifdef __cplusplus
extern "C" {
#endif
#undef ParticleTracking_GPUAnalyse_VERSION
#define ParticleTracking_GPUAnalyse_VERSION 5L
/*
 * Class:     ParticleTracking_GPUAnalyse
 * Method:    cudaGaussFitter
 * Signature: (Ljava/lang/String;Ljava/lang/String;FFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_ParticleTracking_GPUAnalyse_cudaGaussFitter
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
